---
name: Run mutation tests

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main ]

jobs:
  Run-mutation-tests:
    runs-on: windows-latest
    name: Mutation Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
            distribution: 'oracle'
            java-version: '17'
            
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      
      - name: Build project
        working-directory: java_calculadora_mutation_tests
        run: mvn --batch-mode -DskipTests package

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
      
      - name: Run mutation tests in Java
        working-directory: java_calculadora_mutation_tests
        run: |
          mvn test-compile org.pitest:pitest-maven:mutationCoverage
          
      - name: Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./java_calculadora_mutation_tests/target/pit-reports/