---
name: Run mutation tests

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main ]

jobs:
  Run-mutation-tests:
    runs-on: windows-latest
    name: Mutation Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
            distribution: 'oracle'
            java-version: '17'
            cache: maven
      
      - name: Build project
        working-directory: java_calculadora_mutation_tests
        run: mvn --batch-mode -DskipTests package

      - name: Run mutation tests in Java
        working-directory: java_calculadora_mutation_tests
        run: |
          mvn --batch-mode -Dmaven.test.failure.ignore=true test-compile org.pitest:pitest-maven:mutationCoverage
          
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
            name: Maven Tests
            path: target/surefire-reports/*.xml
            reporter: java-junit
            fail-on-error: true